services:
  cognee:
    image: cognee/cognee:0.5.5
    container_name: cognee-sdk-local
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - ENVIRONMENT=local
    volumes:
      - .env:/app/.env
       - cognee_system:/app/cognee/.cognee_system                                                                                                
       - cognee_data:/app/cognee/.data_storage  
    deploy:
      resources:
        limits:
          memory: 8GB
volumes:                                                                                                                                        
  cognee_system:                                                                                                                                
  cognee_data:   